apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-ghost-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: default
  accessModes:
    - ReadWriteOnce
