apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-ghost-depl
spec:
  selector:
    matchLabels:
      app: blog-ghost
  template:
    metadata:
      labels:
        app: blog-ghost
    spec:
      volumes:
        - name: blog-cms-volume
          persistentVolumeClaim:
            claimName: blog-ghost-pvc
            readOnly: false
      containers:
      - name: blog-ghost
        image: ghost:5.2.3
        imagePullPolicy: Always
        resources:
          limits:
            memory: "400Mi"
            cpu: "100m"
          requests:
            memory: "150Mi"
            cpu: "10m"
        ports:
        - containerPort: 2368 
        env:
          - name: url
            value: https://blog-test.cscms.me
        volumeMounts:
          - mountPath: /var/lib/ghost/content
            name: blog-cms-volume
            readOnly: false

