apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-ghost-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
