apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-ghost-depl
spec:
  selector:
    matchLabels:
      app: blog-ghost
  template:
    metadata:
      labels:
        app: blog-ghost
    spec:
      volumes:
        - name: blog-cms-volume
          persistentVolumeClaim:
            claimName: blog-ghost-pvc
            readOnly: false
      containers:
      - name: blog-ghost
        image: ghost:5.2.3
        imagePullPolicy: Always
        resources:
          limits:
            memory: "450Mi"
            cpu: "100m"
          requests:
            memory: "200Mi"
            cpu: "10m"
        ports:
        - containerPort: 2368 
        env:
        - name: url
          value: https://blog.sethanantp.com
        # - name: database__client
        #   value: mysql
        # - name: database__connection__host
        #   value: blog-mysql-srv
        # - name: database__connection__user
        #   value: root
        # - name: database__connection__password
        #   valueFrom:
        #     secretKeyRef:
        #       name: blog-ghost-secret
        #       key: MYSQL_ROOT_PASSWORD
        # - name: database__connection__database
        #   value: ghost
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: blog-cms-volume
          subPath: ghost
          readOnly: false
        # readinessProbe:
        #   httpGet:
        #     port: 2368
        #   initialDelaySeconds: 30
        #   failureThreshold: 6
          
            
---
apiVersion: v1
kind: Service
metadata:
  name: blog-ghost-srv
spec:
  selector:
    app: blog-ghost
  ports:
  - port: 2368
    targetPort: 2368
