---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-ghost-secret
  namespace: blog-sethanantp
spec:
  encryptedData:
    database__connection__password: AgBZdGEyPP4ay5fiHffdEuO2py2SF7MOI0DV22qFu6oxs53TLcdXcRqCdk+WN5Y+gSJdFpVWjX69utT7MoOTZS2A02O95MKdm2h6qaYWHVROZWeKBBavFaEL0kVa0YZxR8j7gMxWexbUFVj4zUtNlMwBWs63LBFbDvVZlkVOZomWq3UU5lPWa3Q3nuqO/TDTDt9W5lKVbDeun0eL4vsyzGkdrMXozKuMmKTJNcvjXjIQNTEfsqaiibGbTCdnqXq1BvYE2mLAgaOHi9BdHZDXBKw1UWN6q0+8OSeJ3fph/TNG6vNKMylIg0KoLtTfxJtOT+ihzIs3rjMVbp5CtXh0E5ViriaS2hM4t0jOBxewaWefwwimp6XiQ8m8qi08ojfbMHAkERCefl0AOrNd1tt55SO1dj9EfPlGXFEfG3/NCM479dUiy7ITK/qgelfVxMZ5w+u5B9pjDMAjFfr9VSC4j9h7qgIfPOpjNL/1exUpPJj+ZU4Z3zWPOR2beYLPXbGG5SJdnwZR48k1Bq9C6gInaXQcZmVNeb79/S1MI2DzNj+xHs3rUOUSivzXySZwuKtXW+6ZwItnLaj2q0hHK4qIyW08iP2BVUzVaB1fajhm4q9PgaVsudB6moCCXQDiaNxiLt/sx/JG7Jt90+wCAZ3qhH32CyMp+gVE8Me+KW8dVpbJUxY5hU+Yq2e4I5AQyEOfJUq+ZxbFj0dR6DGiFzEHXW1OTPEAQpp8J8NVFLg5XVbTPJotOQElyph9
    mail__options__auth__pass: AgArQ2dbVpH4FsnSDaRCTdhfak1IANPCm5Vn3cOMOrdOoTHrbJtnFsN1VDahrPG6Wp4VJFsfoSc6bxt8tx5cVf/cEvVPoVn8M1PNfJhNCu4zTxFdJilu7y+Ceq7p+Ex2p3TEqUFVhFUlcFe4SLHQ3O1c0xHRA8zNLlRDlwbto0yfc5mHnQkia8WFFi1LndqerzTPGAKASy8a/ORzWwfXBZSosZBCgVgHZHqxOfqRW1/RN9DWk3dHeybu26kPmJb0EBwbuZYPw7suWlFSXqSaMnCyAYGmvzB6qaNjXTvueHe7dOUh7RixlXFnnnMMFt33BhUezwCVSKr665Aj7dVFYHdMITp++2gQPZPrEE85Dds7S9t7AFFo0sgfTGv/eVO7Q8tuZB7opLsottaqkeZ4nMcMQXe8U0gIYhq8cBtpeESp87DQ+ot4HDUZAwSKTodetb5MqXJ+C/uom9nyQXGPTaYlh/NRJGKRe7zTOwOJBs37okGakoGIshq7GRzaDa4scvxpZJN0Y3CTwFCfJzune6mhQeleBNmx6bsp290EW1DMDfy8w+wiOljEPVgz0Ok519yKK1YHaTIrKSlB9eZhgJl/qY+Ig80ur+l9YsgR+k1hPn3uCOXx0YwYKva3jO91Qby9rUq2v5BcyCsggZ+BAbmhB1OZiYU5MenTovfYEEKU5CJj0Mcqoqsu0fzkuyDvvu3f0QVh/0xtsBaXPtI1B8brc+IEjCxw9L+gz3gELcYNK23Osbr1pHNpf+80Ot16Be9E/w==
  template:
    metadata:
      name: blog-ghost-secret
      namespace: blog-sethanantp
    type: Opaque
