apiVersion: v1
kind: Secret
metadata:
    name: blog-ghost-secret
    namespace: blog-sethanantp
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:P6jblXcTYR4lmpuJ0OotGSkmQbvdcCZdbnm6AkfXMjY5oub7qnn4+Q==,iv:6H6GWgn/fhFqoHvdtqdu2+Ybo810xbQ+HVsGKEohckI=,tag:YFbgsGYJN4zIsXW77X/Rsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvY1kwZFczQkFPdHVudGdB
            UFdHYWdhMzFZcEI0WTlyKzJVZG4rT3RKMG4wCkdXd0RFYWhmNXRtTFlCc2NVUC9i
            TjJrMm9SUHV5VGxPYU9tTXFFS3lyQmcKLS0tIGx0SzI4Ti93TnNtR1MycjhQdVAx
            WHk1dUoyUnIrUS9vV2FzeW1xb1NaYlUK7wFEjMUnW0owlThgBdHVUUgGhFsip0YH
            jE6RTuwdQ4Egr+QOKC0X4lKOV5/hDvy42RPjE+1Z5cvKN7ls+bldKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T03:09:54Z"
    mac: ENC[AES256_GCM,data:3rTdWNatNn+P1FsXbg00d0gT7Tg3VbmepLECibd/QWebI8DX/8RYeBEnmHyjiX6rfLcJQ3H5Tp+dGqEw8kRHT36ibVaktiDQ6sz04Yc6rt3Ztkwwzvl52Ysc8UU1bjVRTIw355IKmRbV2yiZHC1uIYYuK+dQS9nDFuiPlQ08r4I=,iv:h2jE4vtllxZdsT9y/tDCS86X8H4iXRMy4k+PJEYJx8E=,tag:Lcdscc/EYgCSnw1oA2JL4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
