apiVersion: v1
kind: Secret
metadata:
    name: blog-ghost-secret
    namespace: blog-sethanantp
type: Opaque
stringData:
    database__connection__password: ENC[AES256_GCM,data:Jz6yXZY2R05l90Q6oQZ87bDiO9g6/70bjRZzhelT/26R3ENVhNdkiA==,iv:4YKXq9SeMgha7fEwGztjCGlvq9G2hnAzmKHcXaevOTs=,tag:ZI3j6+oNuyRzel04N9kL7g==,type:str]
    mail__options__auth__pass: ENC[AES256_GCM,data:NRSia9OLrrpL4LGj/u8aV98QM/FdvjJkdQ/Zxv21mql8xhMeryu6gMRyoKC/yWzVVe0=,iv:ueYi3dfSP4YSGMKnDQJnDeTWDYSsK1qgWzCLlXTBctI=,tag:JxB0vMsJHPlsPI2Oc+0Q1A==,type:str]
sops:
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTckVqMGJUeUc4MmJOWFNO
            VUEyVU1QUEFkTUgwdXJzeUNqaWp5RnBqdkg0ClRsbWNpK2pqUVZTNmsyVmpZTVMr
            Y3k1cy9BMjI1cmRIM05iWmEwbit4SU0KLS0tIEVwSmMyRkIyNFdpNmVqRGQrUmVF
            MWcxajI1VmVoa3UyQ01IYTBxZjNhMWcKi0HtDaY5KuiW2zYH1y1B4dyeCDAdgL33
            s8Vbl2akzu5bW9i0N7em9IStiBtgLvdVW5vSez0EJXvITnwHro4uXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T08:40:56Z"
    mac: ENC[AES256_GCM,data:U+7EgtJMtDhNsE3XK1mhDsLq581oo1mhfESUzDMjWRjFTCTcr63FzCoW8poru21G0GUNAM5P3zjj/wMy/bjweEpxoUpDwiOCO26fN8HnIw3BbI4RSaBVGRfcegd51q2W5sbvv4VNyJFeu7FCI+E+iP+OkPdLpp+34qIevEMH3SE=,iv:OoGwpBw4AD+QvB7OjxzSrK2hLqY2JIEyxQNf8WoIqbY=,tag:Oao3UFYbhsKqUj5hO4HRPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
