apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  namespaceSelector:
    matchNames:
    - traefik
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    scheme: http
    honorLabels: true
    interval: 30s # Replace with the desired scrape interval
