apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone-sync
  namespace: adguard
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: rclone-config
              secret:
                secretName: rclone-config
                optional: false
            - name: target-vol
              persistentVolumeClaim:
                claimName: adguard-pvc
                readOnly: true
          containers:
            - name: rclone
              image: rclone/rclone
              imagePullPolicy: Always
              args:
                - sync
                - /mnt/data
                - cscms-k8s-backup-crypt:adguard
                - --config
                - /config/rclone.conf
                - --stats-log-level
                - INFO
                - --log-level
                - INFO
              volumeMounts:
                - name: rclone-config
                  mountPath: /config
                  readOnly: true
                - mountPath: /mnt/data
                  name: target-vol
                  readOnly: true
                
