apiVersion: apps/v1
kind: Deployment
metadata:
  name: oj-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oj-backend
  template:
    metadata:
      labels:
        app: oj-backend
    spec:
    
      volumes:
        - name: oj-storage
          persistentVolumeClaim:
            claimName: oj-pvc
      containers:
        - name: backend
          image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend
          ports:
            - containerPort: 8000
            - containerPort: 1443
          volumeMounts:
            - name: oj-storage
              mountPath: /data
              subPath: backend
          resources:
            limits:
              memory: "512Mi"
              cpu: "50m"
            requests:
              memory: "256Mi"
              cpu: "15m"
          livenessProbe:
            httpGet:
              path: "/"
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 6
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: oj-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: oj-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: oj-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oj-secret
                  key: POSTGRES_PASSWORD
            - name: JUDGE_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: oj-secret
                  key: JUDGE_SERVER_TOKEN
            - name: REDIS_HOST
              value: oj-redis-srv
---
apiVersion: v1
kind: Service
metadata:
  name: oj-backend-srv
spec:
  selector:
    app: oj-backend
  ports:
  - port: 8000
    targetPort: 8000
    name: web
  - port: 1443
    targetPort: 1443
    name: judge-server
  

