apiVersion: apps/v1
kind: Deployment
metadata:
  name: oj-judge-server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oj-judge-server
  template:
    metadata:
      labels:
        app: oj-judge-server
    spec:
      volumes:
        - name: oj-storage
          persistentVolumeClaim:
            claimName: oj-pvc
      containers:
        - name: judge
          image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: oj-storage
              mountPath: /test_case
              subPath: backend/test_case
              readOnly: true
            - name: oj-storage
              mountPath: /log
              subPath: judge_server/log
            - name: oj-storage
              mountPath: /judger
              subPath: judge_server/run
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "180Mi"
              cpu: "100m"
          env:
            - name: SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: oj-configmap
                  key: SERVICE_URL
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: oj-configmap
                  key: BACKEND_URL
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: oj-secret
                  key: JUDGE_SERVER_TOKEN
          livenessProbe:
            exec:
              command:
                - python3
                - /code/service.py
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - FSETID
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: oj-judge-server-srv
spec:
  selector:
    app: oj-judge-server
  ports:
  - port: 8080
    targetPort: 8080
