apiVersion: apps/v1
kind: Deployment
metadata:
  name: oj-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oj-postgres
  template:
    metadata:
      labels:
        app: oj-postgres
    spec:
      volumes:
        - name: oj-storage
          persistentVolumeClaim:
            claimName: oj-pvc
      containers:
        - name: postgres
          image: postgres:10-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: oj-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "80Mi"
              cpu: "40m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: oj-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: oj-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oj-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: oj-postgres-srv
spec:
  selector:
    app: oj-postgres
  ports:
  - port: 5432
    targetPort: 5432
