apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oj-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: oj-pv
  
