apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oj-pvc
spec:
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: oj-azure-disk
  storageClassName: managed-csi
