apiVersion: apps/v1
kind: Deployment
metadata:
  name: oj-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oj-redis
  template:
    metadata:
      labels:
        app: oj-redis
    spec:
      containers:
      - name: oj-redis
        image: redis:6-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
          requests:
            memory: "15Mi"
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: oj-redis-srv
spec:
  selector:
    app: oj-redis
  ports:
  - port: 6379
    targetPort: 6379
