apiVersion: v1
kind: Secret
metadata:
    name: oj-secret
    namespace: onlinejudge
type: Opaque
data:
    JUDGE_SERVER_TOKEN: ENC[AES256_GCM,data:r6JK+SOwf34AMfp/rvKwKD/r3Y8H+SeGPvtnldV8xV8TJistq38Q98eL8vLNtrOVvRdmU/aKmlThWPBwCwbxUCM0RbE=,iv:A3ChrXLk2+IZ/zLzEwnGddLCgXARiSBtvMibjzRu54g=,tag:WzZMfjI0bmC8P2BsTkWDuw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:gsavH8Zw8BcmufiADJVBqg==,iv:fxAG7zwbn6spT/9UHsttkGeCQRcBKQcjki7sJZ2FcfI=,tag:pUR2ih+5YVI73fYZWoIS2g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Y25MjCd3xGOHu4GfD3YkfefMlatOyOi0bQrHL0nDRp4U+WYdejAIEWrVINXciBnIqdQHmvWkO+0=,iv:1DnqHilNO+EYvOi0Vq+YB6ckiVRRvK9a8hu1xGJgOww=,tag:3OconbtZo0GknO61bn+GCQ==,type:str]
sops:
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNGx5bTBtRysxczVsNTA0
            bXhLNlVtV1B3WERBcDJ4QlZYc1c5RnZmOW1FCnI3MEQwNmJYNkpQcVRPemIrNmcw
            emVyamMvQ2huQXQreWlpYm9wSVFYMWMKLS0tIFRNRWc2c3c3OHA1YXkzcENycnFZ
            QXJmZEQ4bmk3YVZjcnMwd0piLzhkZjQKeX9G5f8rLqcX/idGjpKHfBv9ARICrYak
            xI3Q+KgLIoj0rt0wqqL11ORS1X7mB1yAEfagI51qQgiW2hsbja821Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T12:58:19Z"
    mac: ENC[AES256_GCM,data:JUpTKqvyf3Jx5/L3Ju1/x7hw1lFrEztZMJudLXFSs37eBkQC9MDeMh7VveCIu1hHgf0SqjKaATzvkG7bKOnapMtrVnogi6knxaQbMs9MNspNneBPbIE7TMb8+GR7uYXg/jiJ1oKVkxcY2dv2TdfH2bLjs9WNI4BRCvSPPWUk8TM=,iv:x3D3ZyE1AztyHms0ds3Q4Y5t87MYqqK4gTxSYX5rE2U=,tag:omKTXLd20PzdDPtBshvozQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
