apiVersion: v1
kind: Secret
metadata:
    name: oj-secret
    namespace: onlinejudge
type: Opaque
data:
    JUDGE_SERVER_TOKEN: ENC[AES256_GCM,data:bDYYEQfQ2MTJUL1yO8zyvvFDcQAmsxQ4SRIncAAE+1UvzEo0vn3unEBnXUJV86cxRbYl827/O1hKH5TmCywCuUyGYqA=,iv:ZA3IAH9dMy3w77E9HUAuWOI3ruUDUQ4qICnRmcj5/Ag=,tag:axxdELZBKiUvjM6okBcdjQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:7ppt+K0J/Y8HdO+ksG14Og==,iv:8CVSvaVdedkBA0WZU5tIGcgrAq6d30mZgX+HPRSVncs=,tag:mPe794VrcP2f5Q6Zsxc2Wg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dp/2cYhNpYVxl8idSNnChaIFSpjmvxWF+5EKHeDWjIqZX5O7hNXRURDfFOoTJgLw4xokkZu074k=,iv:vfbX6uWn5xD9T9u1IDb1dgIdQ/szSkaOeorLBd773FQ=,tag:kD+tvbfBQ79NnqyJG2z1qg==,type:str]
sops:
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbmN5MDY3OVVyMEk4YVVF
            RFZQVm1zK0JHN0NCVWVOUkxIRmJWR0xMOFdrCmhPNkVjallxTmtoNGJLejlCUkI2
            U1ByTXkwbWhjdDdRRmozMHVBTXEwSkEKLS0tIHV1Ukw3Vm1ZY2FlQmVyaW1jbFhG
            aHppaXhWazhreisvUWF6amFrYWRYWjAKH52zzMu39mtNB27pewZ4dZzPmXwst499
            4W/scrQkNBnlkr30VxbL9mCbHLtZ5j00fYZQnA31y4IDTGJDzlorfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T12:54:35Z"
    mac: ENC[AES256_GCM,data:++qspss7icR2x7/pGkuH0owUMxX3R+rnCcAxS0q/78CoNLcBMryTj586dOPwQDCsovnPvgUQ0xTPwyc9Sx2Z7kmHQknuXJu7vZlIFSW4jjCBt6RvROtyu3xFdZxLjnZi58oJ1K+4xaNwT4MhQIS3FdC4Wn7TWD8AjAqYP1dIQEc=,iv:Gxa2cLA2bsTQHq3HnPSCO8RZsWtR8A5wEiZ1FfDnR90=,tag:CarlntUcEJ75Kd9YAfmHWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
