apiVersion: v1
kind: Secret
metadata:
    name: oj-secret
    namespace: onlinejudge
type: Opaque
data:
    JUDGE_SERVER_TOKEN: ENC[AES256_GCM,data:SoTq2DJN7Mukkffxdf7wsYc5FnW9PVaIiRVJg9eaw77Rmg7PN+6WzNyz+iI22KiJ/8cMsPDOqhbGIpOuA+ufqcv30L0=,iv:rVvsEqnJ7ANy/At9//OxAycX1c6zl5CsRK18SYLDKNE=,tag:MNIiJZ6T+O4a61WjvxFXMA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:FVfj/IThKjUUZQdUVJ7dVw==,iv:IabkEskDtbz0V8N8U8zkw4SvkgotkbNWEitQ/vHTLt8=,tag:A1uSw5Xhxo3zjzA09re4jg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BapbmxfvPIbV/Msj6BC1iZ6YcBhlAXnPxoTCVhmUa5wCFFJWq24mX/ao6tMKtyDtI0kEQUv6QCo=,iv:fQeXjK9o5EfdYlhOS0dy6D9z7Yx3pQdTaeo0ufViugI=,tag:WKBGYEJRPR4ZsE+crewxDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheW9tSCtHZVlzM0JESmJ6
            MUc1cFRDQ3ArcFNBSVBXd01Za2ZWSFhFNDFrClJIdlFsMGhXMCsyNHUyNDI5Tkhy
            NFd2czBMem93M0g3N054N1NtNFdGMU0KLS0tIHpPcUwxbXFOSzc2VU1MN3JIY1lt
            OUQ0dSs4eERlQ0l3NjV5WS9EWFhKNlUKUpwugx+cN4pyUqFOzm29g1iwfQQ5xBMm
            HmCPzwN7ydql8WIDrDLxCOnu5ubnZwKweP4Ms0RAQPbtK7Jqxur/Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T03:09:53Z"
    mac: ENC[AES256_GCM,data:6S0GmxjnNljeYIt9liwRP4YxA8IEEi2B6cpuL6oiAFPLSl1lE91/VHAceF1QBFAIoqJeDdavS+1eA5k6eYpKgspP7ZU3FFkYnqOwqciRlwerC+79VHydv1it9IrNxr777gBUgIivRqAy3IEZME0vEDptVjp39XwGC1BIfgIe7NU=,iv:afbzk1yfMsD9ecUNFTnAkddRj5jes6T4wyR+8bUQp9o=,tag:KA3Yv4DSTUHoaqDTYuZ0tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
