apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress-srv.yaml
- k8s/grafana-srv.yaml

- k8s/common/common-configmap.yaml
- k8s/common/common-mariadb.yaml
- k8s/common/common-pvc.yaml
- k8s/common/common-redis.yaml
# - k8s/common/common-secret.yaml

- k8s/blog-sethanantp/blog-ghost-depl.yaml
- k8s/blog-sethanantp/blog-ghost-pvc.yaml
- k8s/blog-sethanantp/blog-ghost-srv.yaml

- k8s/cscms-intern/cscms-intern-backend.yaml
- k8s/cscms-intern/cscms-intern-frontend.yaml

- k8s/cscms-storage/cscms-storage-cleaner-cronjob.yaml
- k8s/cscms-storage/cscms-storage-configmap.yaml
- k8s/cscms-storage/cscms-storage-depl.yaml
- k8s/cscms-storage/cscms-storage-srv.yaml
# - k8s/cscms-storage/cscms-storage-secret.yaml

- k8s/cscms-url-shortener/cscms-url-shortener-depl.yaml
- k8s/cscms-url-shortener/cscms-url-shortener-srv.yaml
# - k8s/cscms-url-shortener/cscms-url-shortener-secret.yaml

- k8s/onlinejudge/oj-backend-depl.yaml
- k8s/onlinejudge/oj-postgres-depl.yaml
- k8s/onlinejudge/oj-judge-server-depl.yaml
- k8s/onlinejudge/oj-pvc.yaml
- k8s/onlinejudge/oj-configmap.yaml
# - k8s/onlinejudge/oj-secret.yaml

- k8s/timetable/timetable-api-depl.yaml
- k8s/timetable/timetable-api-srv.yaml
- k8s/timetable/timetable-client-depl.yaml
- k8s/timetable/timetable-client-srv.yaml

# - k8s/tls/cscms-tls-secret.yaml
# - k8s/tls/sethanantp-tls-secret.yaml