apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Y+w+t8Q=,iv:3W6Tax5N9QQ70vOKXL3QAvWLPTM3bbA90NfBY6rSBvA=,tag:ZUXSQU3SgK4ARx7hFmkmCA==,type:str]
    password: ENC[AES256_GCM,data:40jwy4LLYEu+JntO+hE1ASNq8d3ManC9JfwarBk2,iv:hzy5iFj57g/x14DJUR9yiir8MO+Ef4kyBY1G+xDDyMk=,tag:KKBnFsW0x6AlCD2xk2U1yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTG1taWplVzlXSWpnWjJU
            U1BjT0Zib3VoZ0R1SmhLV1NCSzRyam1jS0Q4CjhLL01ublVNMkJNYURzeGkwN0d4
            UENXYTVtMUxsdHB5K0JCaWFYZWRmbzQKLS0tIDZEdnBuQWIvZWVRZVZMTVJRRkVJ
            a1cxSW1UTjVtcXIwRmJCa2p3RWlVbHcKp10r9GlvGWsaq211ICwtgWFrfLBzun/j
            MRPEPZ9sz/htx1xU8EO9p9CDjOyTByeqYRhgoLKAXKkExKCMyZZR6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T09:32:07Z"
    mac: ENC[AES256_GCM,data:m/7R2ZZL58ZObWL+9gQMyMuuw88JsuN+7hWRX9mu0atCw0gGVhx7JPpMtdZ00c62k8tIGwp9FlHJGhJVmL+oGIs3Rbwu6R4uBjKwTpBLtfWRpbY4t/Pa32N/n8P+bbIa3GqYGY3WcX7aKg+8DZ5cr79fbnlv0padEB8WsQtu5FY=,iv:o265fwoiMtusM8vPNDoh1ixKum3I1Axgx0BvvTBOzxc=,tag:7y2RMFVBXtigNk6KcKUeNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
