apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hb/ow84=,iv:u4CpqI4fkR6DqTqD+LptcYPPzXRx2HOqTCKquoZoctU=,tag:mnd1pcAuR6+OaDe/Ruzrzw==,type:str]
    password: ENC[AES256_GCM,data:sRokgHhVLbiWnP4tVixTqQlD/zf5a5/1sh0YVAK+,iv:YWvByNjEd7n2cUVvXC0MCGUQo0yJ3d4vR01gu9AjjFw=,tag:b5GDzR37htsO7ZdLwRJuNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTEVVOE45bGhhV3FlNDVR
            WDZJY25RV3JGcXlieGZ3OHRaTElyTy9nK1VNCllrbmdDcDBNb2oxZ2RZcmEwRFRr
            Ui9zd1VwNi9lOE0zUWhDdHVoUUpiZHcKLS0tIFN2ZUovbmh4TjNLdEdVRkVXU0pp
            WFZ4Y0VISnB0YmczMjc2ZjNrZmt6ZWsK+wXOCHHUCiZDb07wpXg8DWrZSjTIBICm
            7vIZ/jlPJuz+of8jUgWnn5NZZ8juJKIBh3fn/dRiPtsiRTOh+dHDDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T03:09:54Z"
    mac: ENC[AES256_GCM,data:7FYfaRmF4RKI2tM1Qjdao1OUsi8nqmCKdHEH4T4/DktB3dJXBdffcYKYpc1wSHCR/Z4uucZ+8bmiRFUzMZAzrMoFHWaYYYO9xbPJw4NvJsSj0Ufbc8mXFKe7v3Dkk3QsSq/fhfLIE7YH21IwBb9N7zz1RjN5XZzNGnhLTXJjUJg=,iv:dH0Rleu15O6kHipJ2W0Mu0kY/2HqXXGYJScb6wf1gb0=,tag:prFXdqqTJ8u5Y6LhBqkT9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
