apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WtdCMpU=,iv:soI6qy5cRpLYn58+oGQ5fVUYcc50PG/HwOZ2UKiJiSw=,tag:ldd0rQxOSVCEA6NUfcbFBg==,type:str]
    password: ENC[AES256_GCM,data:I/+/8RfWz+gnUQ2mnThvBG0Edlx7exP0BTIcihx5,iv:TmBa6RRZMmQ5wbDnEj5ncd4s9P31oaB5w1FHJx/74SQ=,tag:QSYli2t3MPL6qZY24Yjkrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Ukcxc3VqUDhRZmY5LzV1
            ellUeGU3K1RlTHB5L2VZTkJBSEhDM0MrbkFNCnllS25jLzFzNVlQdUh2bWdKUGJr
            aWx6VDQyUkpDaEE5NFVsZG80UEd5ck0KLS0tIC9SMDVDd2V4a2krVk11RUxqa1p4
            TW9pRS9pcFk3REorVnVwUGtjTTJCbDAK70Hq7bMdghOzkUY1s64whq8XdTqGPk4N
            K/vIekYDCaz/BRN5TAJwaSq93O9u4wa4je2g0q0etrLxvM1XFfWpzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T09:41:26Z"
    mac: ENC[AES256_GCM,data:4R5wZcqbsal3VaMxeMjak0h0dgIiFGY63bAthTIAxOtbajQat5kz48qeGR92gErqxVTybBRWLYX80jqeogBhxJrB289gtZkoLgd+JpmN5fjsHvIyWYsSROaCPIfZOMbvVxeltCzI2TAYWt5r4aXAlJjBFj7YL1R0dNSKiudtdOk=,iv:H+HvqnL3LXNY938+1fUMIDQguTXKiCxxlqVA4IO0KYQ=,tag:vr8zfPT6q6m7YRicpptwxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
