---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgABeC7kh5fpJlW1dzPtKKrRFjRqlBJ1F9diI+AiUJK1jPvyx9gLheZTovMGhkUeessn0+4mPwLF6CzeDecthsOouH6RhmTPkQUyaS4dZLHFXptlRGqnIGVW6ZF3UXVFqBBgjXDSNnzA5GDFNwnHswvuYESM3Y1LBb5LDDxp07y/B3zrvpp90W7V/n6J5PnqBf7jQ+Dq90i2dLvjklPZwekZZES/2KR3bTN4ijaG0+HjlaBqmsiqbk6qe68KxFwL/oKBZY1pYe18MaSUVubMnxYayXiA4zgxg5742tApH2wv83ZoshuHPD+NV5tB9zNXDtokiwJosCYkgUNsU7eEsTboT4kh8kKzVTpl8xDVxX1FjYAgWs4ycgV0W+PVO+b9L3szYxotvYLxEbeRC8IKDE09sGyuNI2jE0wwrwBlD3L3EOxQlQESsiN/ljdhaETekG5Lx+4+O2Jr3k9PPCr7aS8/KXrlPqx5lLXEdRiT5Rqqgbj1qLu0oJ6v7Sjj0BOU/Zf/BuIU/8pwef8+/X6MUvKsPSNVtQdpLNzInfgnh2jG2dWUkGwBu4gI3SkzxA8VEC7u7pl4krI6KUW0m/cbEdiEzz4Dz+xVcf947UjD3+flaQEsHaBS9NNLfpx36iQvSN1P17jnUzsd+uC32v1AQQjRgIcAwaTAE2Fl/JJeVg/kLq53p2pfYxq2AEvt+5rSQoI+JteMasNhDfkkF21esFLWDDO/wjVRr6NGojORQ5o=
    username: AgATzXBEc4YuDlEykjRIMn5trCpDZAGnaSsjS5AxqGZjI3YxUbph2/pcLHLELci/g2bqySRPyhGIr+JXCwbCII42+PigePdabZBsyv6/6wNd4snD53XXABzjdHxvyHI0rzR6UxUMgwEsy7qO/JRdgnpaFpynZoezCBpekV94eGoNd5nUrmDgsOoeTAYlRJe6rmbJX11PG5P2juksedJt5lmPCH3ID+rXGGqSFU34RDiA69BiAntBt8kE7iKFraqsWaH19WmDblKBaQhH4H+ktD8hFr8EW72pf1A68d25ZrxmXAbSZRJfjYS6jVJ9Vk6x6HsXyVZDKaGjQoXfGiO2LpSVyHVPQ6p8ap6v0mWM18rHYx71F5MTIu4u3Ux4mbd51iqfL9bheXoHf7sTxCfpTehbLn52bFjBplBPf8qaE/uU6OPOxnotSR/HMlkrTAK2cHwIwqN9Lj9UQLf7PTpjWufA51JZHtQ8zI2P8zsrC0T425pOQltFcJqbUl4pmO89MEfHKm5aAb3S5E3XJnFcTKdEDl8U+T03W9NOzYFmc17zH/d3NE7kJQfGctAkkdpkNz1J4dfuZx0PyTZxAG4qAtlobHOYd0NHKfTkavmanyRapUxVgY1YFGsrJ403Hk2ZXFajqvt/HrwfN9l6zV1GL3tXwbg9M+8IY1XdVH0g5JXlxFDGE4EobqXZq5J7mkU9E5NqXNUZqA==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
    type: Opaque
