---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: onlinejudge
spec:
  encryptedData:
    password: AgB3LOID7Gb+m/Z+uizUby8hQc2wJZkGJJ8Iqt87Aw0GcX1Gy/4uW1/VjNhXJUqGYFFIXLMmvGVgV20Jh0H6neyN0Dm3SgUHNzv11ixLlx50OTlJMFV8odf44T01JdIklx7i6ZvHL274+UA3zGctgkE9daiIwVD4lkHtVhRONfgmigbX1p+hqnkLcaB3PbYQI36zmE/PcLZskc2nNICt6Y8AztyCkEoaBGeSQnBu7dtRqEfuQIuBiyWRpt80xesNDlMnr6hlMKTAb7P/taHXy5vIcLupgF9UO5swa9I0AcU8xfyJr3czQmbV8qsmOp/Hqt6Ygz9fyW1XBI5iIrUV1F92nMTa0JfZDEWipbJfRPxwIjpr3j58Ad4NQC6MAHH9ibkUMMs1pav9XZvzlNm8z8u7LkFujiaPMn+BYvPrS/Kk5Jo2orEIz7r1rk9gXQNQ4zNKdUg61WpCSxP9cBgU4ny4WC7Vf1GCx70rAQuOUH/V+jqnJwkaBEHyNDFwsOp272hVZlTusuNQHn3O2YdaDEfXWZ1NKIhMH1iMgKI12CaPLSp9GXFTppCc8uOAOzdaFizozf8TVMdxL/UFuKtE6BviH5iY8fEJRc4r1oAxZqyChn9NdMVrezTR1hbDYZ4Q/GFKCak/XXolyYCAQBHhb3eGw4YeRO8OCbMSW/ejJZX1si79Vp99TqVHH6Ooj2fL4fxXckU6QBfx2mThV/YWWRC0y5cRXr5o48OhtcQ2vhw=
    username: AgBR8mSRXahObampXzaSAZP/VKPj8G0et8poMEpubj61qs7Sdwqv17wS7BdbQdkiLuFfB+J83J/VOia+55ITyJNYVF5ygmk1jrBdbS8AuSKpCLWzGP4vhIzh4jOV7PaUmLPJPkmEwBwXQ7i+xLd/9lqlD4lJUh30UwBZ5BRdLO7TV9gMtEZwQ/1+JDJeMZBuIBVlarytc3uFPS8er+Fb+FnRxyJy1IkLYJh3Efgn8+TCKnoK+F9km/kZBovluwCoy/pxBWLJmwQANslgcN00Yl65Fcl1VGKVaQSqU80RuLOhPOkZ+wY/7pI0Gy4iIhGhjan5s8iz38nZIxBlhoP0xozrkc/vvUnH6Om1Y0zpqxTNXy7Di1TGMwPOCGJmeXYWwFBlKM7ZaL49LXDz2YX0EH8T5ymlumKmjYmq4BhlUrPSgsauwyI2S5MvjOWCKkj2T1oXyu6ZdluHesLir5jNuX/oZkv0Okh8oDHHhuXq2zB+yQSbPvMd3kPm47Pp81vSjTJEd7Xk1wDwPWDLMrJUra5O8BwWt2h39FbcczJodlvLKyBD1YJbsZyhDBauWeNgAHpnMcj8YWHoQ0wnY5bF+dDSWvJ1IMv7GpUmHEK5U8uu7NF06suF2iSK41ufOFViTNBhDVDX/bu1J72ihBGiuU4zfFAS2CMYVHU8JH0hrq55q+7osQ6ftOj8bt5bHsz1f/KipoW7gQ==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: onlinejudge
    type: Opaque
