apiVersion: v1
data:
    rclone.conf: ENC[AES256_GCM,data:jmN83fdxGOt3gkYLY0IWUFYe7dkcQMTq+ArAnClTT2l4yXh88+DGlqd7fEaCt11REhaeHLgmyIH0HFRGibMCx3Prkfk1PpBOnebGKYZ/UxINpItuAx33t5iddc7VBxvuueVD+Qg3DXzvP08hcdcWIXRfiwyK8NSHIqVQ/8bn/KGo1Md29g9gopNoIrIDQqLn4GbkUoUUlp74gy2ulF1Vpswswhif064cTlZ4vnuvP8eTtwP3ThzqeZTW2k6cKORadSDHYABofli5HK8v3QMjLlicOMNNhTtVjQH8FYx9llCcovm7KedZOGHE9NMSRXSqFpLn7nQvR07bRNH87bBjCK06K2U047kG88iDT5FTPtrf2OaVB3yzdFB2vGhzSnWY3iQQkmbLkgPY7ll5J3aCQro04zOCpghWiM5fIhtgj/i7GgSr0E0I9JfpFNGBsFnHU9u928Wuvxkvxb2ccoEjgBTQojR+T7CBTbGPWNP4L/97hQ4NpcBtPzTo3FgBDq0mCNeXcyt+n4mkgzOTVx29qQErOWMtynQlcQ3J5HMZG/o52Fyc/JfCvfcjKgioyXR6opMDDO0zS8BDIp8cEmNh4h/aIbYJu1KcJ9B3lpq4HO9eHdA0brPeYtiu1Pl7nVGNxOS9lUvm+vfc8EyE+nS5+6PfcwsMTX6H2AXdmUCN9DaQyXHY6svz69ax+BG6468tJkXQYuG5YqwYGNTI8Zafx1dVag4=,iv:hOEOmGxHiuTAjO7zR3s2rGcYhCeqNoGeNP0l6LfqtiU=,tag:zjkVO0mEodAB7zn33aXtVA==,type:str]
kind: Secret
metadata:
    name: rclone-config
    annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TURHUDVxLzJvbXBrWmkr
            bjBFQXhCYXRjaVRCTDcrMWlRb3YzNDI0YkZFCjErRzZ2UWdJVFcyUzg5ayt5bllG
            WjNqZWJZZktRZ1lNYlJaSU16cGRFd2MKLS0tIFVHZFlWQWNuSlVHZWUvakkycDNx
            bFhaZnhQSXhMNmFGNmlsdHJxay9RNDAKKzyI+WW5kZNbE5OfTkL+TOw6/U5K7ZOf
            R5eDDIenxo8DnPcbDpjQ9MSmcNHvoZ4JghKFYT/Kc3f0BbreX7gPOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T03:09:54Z"
    mac: ENC[AES256_GCM,data:4CTMlu1dVSNKKQooiozPSAk5O/+dfmV8KvxgiVSS4Be8iQkUXBS+QfCepidgZu3inJ3uwvm19fDLegf9O0i29W8lcPj+Cfkp0kTHZWLDhL4Z1aXSzGFHf8N0tHamgPR8oPez7sLw0EtgVurogqB4zv7O9GFwDq9BwUAZiDE25o0=,iv:b6l6i0T54+/BCoqNwjqQiHs8CmywgqoPHxPgLIgfQ/4=,tag:W6epujL6eYCCJZem8KtclQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
