apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
spec:
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  
