apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/limit-rps: "30"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts: 
      - aka-test.cscms.me
      - timetable.cscms.me
      - storage.cscms.me
      - tmp.cscms.me
      - cscms.me
      - monitor.cscms.me
      - papaya.cscms.me
      - plex.cscms.me
      - crypto.cscms.me
      secretName: cscms-tls
    - hosts:
      - blog.sethanantp.com
      secretName: sethanantp-tls
  rules:
    - host: cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: oj-backend-srv
              port: 
                number: 8000
    - host: aka-test.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: aka-cscms-srv
              port: 
                number: 3050
    - host: timetable.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /api?(.*)
          backend:
            service:
              name: timetable-api-srv
              port: 
                number: 4000
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: timetable-client-srv
              port: 
                number: 80
    - host: storage.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: cscms-storage-srv
              port: 
                number: 5000
    - host: tmp.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: cscms-storage-srv
              port: 
                number: 5000
    - host: monitor.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: grafana-srv
              port: 
                number: 80
    - host: plex.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: plex-server-srv
              port: 
                number: 32400
    - host: papaya.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: pogpog-papaya-backend-api-srv
              port: 
                number: 5000
        - pathType: Prefix
          path: /line/?(.*)
          backend:
            service:
              name: pogpog-papaya-line-bot-srv
              port: 
                number: 3000
    - host: crypto.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: crypto-price-bot-srv
              port: 
                number: 3000
    - host: intern.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: cscms-intern-frontend-srv
              port: 
                number: 3000
        - pathType: Prefix
          path: /api/?(.*)
          backend:
            service:
              name: cscms-intern-backend-srv
              port: 
                number: 5000
    - host: blog.sethanantp.com
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: blog-ghost-srv
              port: 
                number: 2368
