apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts: 
      - aka-test.cscms.me
      - timetable-test.cscms.me
      secretName: cscms-tls
    - hosts:
      - blog-test.sethanantp.com
      secretName: sethanantp-tls
  rules:
    - host: aka-test.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: aka-cscms-srv
              port: 
                number: 3050
    - host: timetable-test.cscms.me
      http:
        paths:
        - pathType: Prefix
          path: /api?(.*)
          backend:
            service:
              name: timetable-api-srv
              port: 
                number: 4000
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: timetable-client-srv
              port: 
                number: 80
    - host: blog-test.sethanantp.com
      http:
        paths:
        - pathType: Prefix
          path: /?(.*)
          backend:
            service:
              name: blog-ghost-srv
              port: 
                number: 2368
