apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable-api-depl
spec:
  selector:
    matchLabels:
      app: timetable-api
  template:
    metadata:
      labels:
        app: timetable-api
    spec:
      containers:
      - name: timetable-api
        image: thetkpark/cs-timetable-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "20m"
        ports:
        - containerPort: 4000

