apiVersion: apps/v1
kind: Deployment
metadata:
  name: lm-code-distribution-depl
spec:
  selector:
    matchLabels:
      app: lm-code-distribution-depl
  template:
    metadata:
      labels:
        app: lm-code-distribution-depl
    spec:
      containers:
        - name: lm-code-distribution-depl
          image: thetkpark/lm-code-distribution:f84a693d702fc54bc2f6857126b453ffcf48a67f
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "50m"
          envFrom:
            - secretRef:
                name: lm-code-distribution
                optional: false
          env:
            - name: NODE_ENV
              value: "production"
            - name: ALLOWED_USER_IDS
              value: "834716830"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
