apiVersion: v1
kind: Secret
metadata:
    name: lm-code-distribution
    namespace: lm-code-distribution
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:deCBbuISRYVuE6byqUTYT56GcvEtRLsQ/5jGdK567fSv194wxBUP8rkMDs8W6YEUkPP2YFPdCHdKdUWF2cAmIQSKCPLaRkpnr09knaMV3Vg5TTb+9jzIeH/NFSe3/KPcr1OFOvsENRMPxbarEN2t4dc6Kg==,iv:jxcZN1Gco3ql2R8dW1XUftoUpQudnYWIXXDdCHYRrqE=,tag:drzXQbU4sQ66ASJAWGbtsQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:AckXTWY4Sq0w8QkKSH0xabB1hDnijqF0ijqDuHCbb5TLf4nLgU4bEwkOOSKl9g==,iv:zKVxXLNL/FwoY/5is0LWS8zLaiDdLYVD46vvLUf2EfY=,tag:yXZdAYNUIjzYRleuSrrAPQ==,type:str]
    MAILGUN_SIGNING_KEY: ENC[AES256_GCM,data:nUYIE4I9FTmWUf1643o5RlwnRJN/7lUtZsOlUG6Z6SO3b5bZWkIjHmC+SB9kNOQAboE=,iv:1ewStFrxoBjET45kRi0wiRCMWjf8kGU3vgqYRs6hDFY=,tag:ndTjp+x9wDAhGMnfjYW5Bg==,type:str]
sops:
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bE9hNlJIOFU3SzRnL2NO
            dVhrWDdadEU0U1BsT1BodWQvekRjTUxoNkRjCjhVZHdBRkp2OFRYZ3dzb3FCOUFH
            bnR3NzJwWVRrVzY3UlJ6bTd2cUNOZnMKLS0tIFZPb0hMRWZ2eWRERlpNM3NuMDll
            TTNGM2NuZW9xbG16ZVorY0NKd3RxSVUKAj0FR+Ewl/Tb7Bowt3iO3DFS3yVrICJQ
            Qi7xvc2gOUmpCz/JemFqb2AwqYTynDf7loVNBEdcp+7+eu/dWJIqvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T16:20:19Z"
    mac: ENC[AES256_GCM,data:t4apu3FH4AYuqP9SVYivxXSqvLes7T0dmY30Sd5AFN1MxgWCXqcpF5CuzUkxYEvJGmXgjlL5RCx+6qWcMvXtJvKXwpQRRkgaug6LVbi7P/f1RkFB0WclI/wkRrwB7dqOJzoqTH09A69XVLn2dTjzy1+sXfTyb2/kK1SOblRqP7k=,iv:uA46vydGs1HxsW3jq0+mqudUoLsKvtTiomyKIpVQ5no=,tag:Ky3BGs62IEYmFe/lxubc/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
