apiVersion: v1
kind: Secret
metadata:
    name: lm-code-distribution
    namespace: lm-code-distribution
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:zkexBLMC3NPwZSwPQICZfwPw5tI7STNfPVW/JqZHUwW0HCNUFdgp3BKgRkfZFk3GfVdjr5BpQMWU8807lPnrAlM4FQVTKPzBWbRYsU63IplMtwm6zDaM5sznYs6rC1ASF+BNuKWCOYkTlVI60VTlarQYDQ==,iv:tVViUbhSJZ7GAVbT5dqOHAg90nH2ec6gQWSr5oBoffA=,tag:OZWCHnRX7CgWuTeOCajzvA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:kjvIOLqr/8l1BEhu/MjnaqCWiN9q2RLIGDD00mu8ttIQopF4nw2LIHSgMHfEfw==,iv:9b268BoI8wHDbnQWmTuw4eco+DItOOLmF528UUnpdb0=,tag:MDEZP/sikDNUUOzYl/286Q==,type:str]
sops:
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSGlwWnI0WlhxNkNsNkFn
            ZGtzT2R1QnpUNjcvQWYzb3VkWk5IUWlzRERRCmc3a0tTYjIrblpEMGxja1pRMHI0
            c0JqSVVMR2Vsc0c4K0ZsTitOdzJJMkkKLS0tIDFTZ3BXWitYWmlKZWVTSUh4Z1NR
            WVBtazZHK1JnbDlZZUNZb1RrbFk1MlkKpZenJkYDIbRHyZ1LXTzwuvCZlwWjG6Sl
            psuqf6Qaf5IF411xDzSo4ykEP0x1A4v5qbKcD3GKIwBECxBPEfjnAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:54:58Z"
    mac: ENC[AES256_GCM,data:ZvmgAg8aP0AXYmPYFZJyLgbY50VKF9gP+fEeZestJMXTKVT/yzUGDmmoMfTK8C5Sx5T7f0Rvi3v7r22ac/zDfnVk0GIiQFcxhoitvOdwGDfm8xg80tCAZOJIonqHY0leG2BBYw4WBCRtQV+leQ/ptjsuRgRqmgDoP7K+tVFLRUk=,iv:HETdlhUxrJMQc1LXElw07EEpoj391DejLUAP3fjdVFI=,tag:++DHpjOBlaAgLzxVt2LxBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
