apiVersion: v1
kind: Secret
metadata:
    name: lm-code-distribution
    namespace: lm-code-distribution
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:17jvTEmlwj2eLjXvciszEAVbGGlOWm5adJSpakoLrzq9bv2bDlSVH6+DLiDiTkly8R5YtGuKSn6zd9sO3q+U2dRiXZ+ykX66EwpHSW7RcAJ5yOswva5Pwau3noDs0dqECaGpCejMRFmgxokKGoOf852ARw==,iv:Y73YVxpz0kPoEudbuVrJDBwIchaMlHyPpy9FaHLpfB4=,tag:n4NGCpHIMFrg/DgITxtsFg==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:o1XSjTRSmTUj9A6iWxWCjV0Vc16amDqwYAKk90O+Yb+4A4YtoM2auzcYXLrFAQ==,iv:BMssYNsMe72Qjs5cpRSTgRntms0cD1BIANblpRLj8U0=,tag:OvzmzxyceAnFLT9rfd3x5g==,type:str]
    MAILGUN_SIGNING_KEY: ENC[AES256_GCM,data:4Bc5OELdYf4dNVVGjBSRfwajOc6j+W5f0VLyt/FnccQmjJQYNtRGilc/jsTUzNzl8ZU=,iv:28EupA+EfnUpMUK2w9tCdWQ/qfpYKQg6yvyz9m0CQEk=,tag:+Iwtb3yVFIcbmtpwZrYvxg==,type:str]
sops:
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSDdKNWlOelJaNk9lbGdY
            SWtVbHE1OFphdkJkMFNUcjd5c0wxQXh5Q1hZCmVkOFN4MGxLOUU5YWQzd1lxRVdr
            R1BiUHQySkwxeTdRWk1xMTVkSWsvalEKLS0tIDgvMENERm4zTGQ2MUIzdEVZbFJz
            VnNTdUd1T1hRdXRXcCs0emZyWG1MeWsKDDEYlrv0XlmvPXMqX2jSZ/AMmfY70fS5
            3JxDhv/PCoI1radJBj0FfMAT9RJqcC1pDpiziB8An8xDMMly1IfVLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T16:27:50Z"
    mac: ENC[AES256_GCM,data:pF0MBx/3H52SpTWvw8cAHCF5xXKvjKqmPwgGDZMn0NbJEtm5MyFFKacXErpscoX+n9Idra57WwnyK7gPc1DzF3JSllgL1EAye2dkpSD1toNDobDnnNd2bG2RP6RRn2P3JDPXEdaoDHAQddIQ9ZUFp8iuCn8dTS1hrtjGPT6q2P0=,iv:mfn+8ki5lamVRbHelknUXzp2IN1GK9mo8aG3wPqCRZA=,tag:WHnhTGfHFyGKVMoSo6/3Pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
