apiVersion: v1
kind: Secret
metadata:
    name: pogpog-papaya-line-bot-secret
type: Opaque
data:
    CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:R8ahvNNz51zA/P8A15pLqkKc24PX2LEa5pVagZDbeECt/OHyNSHhpmfQaWoW3tbZDccSxEnTe2M8ut8PY6sLU5MsVHvzCKdiBHYPgEuNFr91noZdSVpgkz1ghY9zF0KSCRNmtVcUxoarMEP5cPACKEa1y9CjSgwriJkrnGOTFTDauiKMJ/4mHHjn3Gzb1eQIV5z7RWh5Ltj0eVS0BDvFqdoblWL4kJhHbQ0TR4AVWy9kQ0lvwLWwUD3Z4vPj7PWrUt3MBhzTs3l5SsLfKyMrzk3Ks5usUMCtTtc8Vhz6nIYFoqe39S1kgw==,iv:Hs6gq/1ENs1w5GFRDjrrdmn1gGv73poCH7nnqlJIUkM=,tag:zyg1R0vU3SDBF3MS0DKdtQ==,type:str]
    CHANNEL_SECRET: ENC[AES256_GCM,data:CE7/29D0xU/KrLjZng7QFxS97s9sYkB0kQTqBnl9mED6qlbfjC2k28PdvV0=,iv:Kq5D+2ZvzKi9vIf/YlSj3jzKIlPFI1MT3Bb/m6wMWrA=,tag:kY6y+JY4UUJP8QpnOL/6rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://cscms.vault.azure.net
          name: cscms-k8s-sops-key
          version: bdd9127145c441e2a5d1628e0d32c706
          created_at: "2021-09-03T14:39:49Z"
          enc: aCjAxSqSFpv8tJmpk4v_lhTp9YKvNl0aq4lsczb1WEP08tcRY-UC2zZml98gUbVM59SoUVjNx3erUmi9qyVLkzjvmy4oNu02mKgcG7nzuq_oF9NahIICHtQW0UD9yTdSwL2C8YoRAqTUzotnSG1QdfcXZlPS7va67duioMQwr9PPftG_YV-dVdV2TqjbNmsAXFvWdobsrfKyFTqbfd2cIYzU8Kcv1KCx8PCPsBUEHbJET1PjWjcAIy3cXwuFNdXew-ZI3g3yQ8DSQNtX_iYK_J8Y4HdRyw0fufhDcWXSbhduxYtbKoHMqcFruoXuw-osmMN-wFUMJySBeQ_VmUn9XrRUG1x98fWvZqX0oQL7ZHZ67TBD-Qfx7qY-kVFpU4fK6LlrrhuKRY7-g930eraW2lm3j-cYUxFVBfB8hsRevrVd06MXWcFauVBwk7c4ypcd-RreXxpaw59EGuwRN3OwNbQMtDTKlUHy8olBwaUQBMYeeFB99DkJT3xA6i_LKKVa
    hc_vault: []
    age: []
    lastmodified: "2021-09-03T14:39:54Z"
    mac: ENC[AES256_GCM,data:CYodOugCtz+eAhA6eptQOj/fW54vbqVhgUHHDXspXaVr1/IMmx2dzke5xt2DefMF5fnGcL3JFA2Cs5kjsCFPh8XslKDUVZyNpCkxa4Ap6mRSGH1qTMrT2uLasakImrYezw44ZQwye+aVKg0yVWsTsKEOMfjyakVhaXrnwwxvSmw=,iv:lRoo2toiiakRCLvET3h/rvTGYI3o7UxG2DV/qFMYNB4=,tag:E20Xwnf5rgSxJOy6TM6yVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
