apiVersion: apps/v1
kind: Deployment
metadata:
  name: pogpog-papaya-line-bot-depl
spec:
  selector:
    matchLabels:
      app: pogpog-papaya-line-bot
  template:
    metadata:
      labels:
        app: pogpog-papaya-line-bot
    spec:
      containers:
      - name: pogpog-papaya-line-bot
        image: thetkpark/pogpog-papaya-line-bot
        resources:
          resources:
          limits:
            memory: "70Mi"
            cpu: "25m"
          requests:
            memory: "40Mi"
            cpu: "5m"
        ports:
        - containerPort: 3000
        env:
          - name: BACKEND_API_URL
            value: http://pogpog-papaya-backend-api-srv:5000
        envFrom:
          - secretRef:
              name: pogpog-papaya-line-bot-secret
          
