apiVersion: v1
kind: Secret
metadata:
    name: common-secret
type: Opaque
data:
    MARIADB_USER: ENC[AES256_GCM,data:GcY5AA==,iv:Lb46ee8yuQcks6yJtqnHmMH74dHhe15yAPYMMgR4k0o=,tag:psbGlvDfGcQzSCnK+d9z4g==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:uR6CjHvsFlTJxoIaA1xlXjwTqObSXI4/+itEb6AFqqZ57zQB82CsGt0vRXn1CR5Ru0Z6ijWvlbc=,iv:tB7JKat7sbaS8on1JpFA6FpQNrRH10gKLecF8tZNkRQ=,tag:lv7mnjClCe43JgPece8FiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://cscms.vault.azure.net
          name: cscms-k8s-sops-key
          version: bdd9127145c441e2a5d1628e0d32c706
          created_at: "2021-10-26T09:29:37Z"
          enc: rviGLKovq0KRSHXEFyv2VuZFAh1fBIc2QuK2EMN-L36evzTYCbxsys-9YKpGfWVwGN9-XwrOa8OonnQLLiVrgUo0-2_OifVQfiN-TR2ATTJkkSt6LuyvRaMJwBkELGB7zM5h07ZHWD1mLwEG3AdhWAgrBo_o8b4-JaUUy4J4frjsypY-p_OOmwHI_LNK0jxX1aO_5yAOKI_cX5cfkrO2hJmgOpwYp0xo_QXe_RGrpebSjJm4ju8FtKsD7Gt4viwLcUS6-Sp-CWMzAwNIHEqLu8tjDQDuoy6l4buCSm1cM6kGhguvvEnLWzr6Uqo3Zo7zLYNUZ0yafZBUNt1hdIrNP0vXPJ_JUkc_2sDW3nJxfHDrM9OLMEDXA8DA6XJPk7TZZynNTwauOx9tREXKxz4gMx1LgRDGajhl6oUhiQ4VONY9JjHkyShFuJ96pR6rhDvbbfmC4mO1A71ww7ePNNge6fOXZhNaUOJyl3d3TYmDx5-JLcxIXKQ2QlSIMIxn_gn7
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T09:29:41Z"
    mac: ENC[AES256_GCM,data:U2p+tD2NsZW/SdiGtuMbfvltmbdFDud+Z+tFabTDt4JWCXpC0vyuaKGmP5ZvlsWLuxQtHJ7Kmwamc2ytR1viumOT9Fs+Qw9wBmfDrh4b6xFFAkJDl1I/SMBP/UO/hKIibP74/IdSyJG0NAsyAEnOWUIpUjto611i6x+JE7V2Mk4=,iv:iLocywjIrTWjp4YqW9lE3XL/E3kUsEnZFJHyZAHc/Gc=,tag:B0HaVmsJRnPMTtTTP/Nkcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
