apiVersion: v1
kind: Secret
metadata:
    name: common-secret
type: Opaque
data:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:dCuVgVUAepI1RTjRm/SjdJN0KwtKhiq3X9FId8K0jDgxGMoFE7dKdfSnRdIkgpDN4A97oVTWQTo=,iv:nk9snYelWPdfsr+hs/euBUsgetm3DFEDAkKUqfE1L4U=,tag:vJ566siL/z1jsWi3MtBJZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://cscms.vault.azure.net
          name: cscms-k8s-sops-key
          version: bdd9127145c441e2a5d1628e0d32c706
          created_at: "2021-10-13T14:42:31Z"
          enc: AA1HbJl8Tyc90ssts35K-j-FlST_IYoPTcekMv8_tGFisMeKaEK0vDu765L8v05uSI-reBRRFt8MIMcHl2tTtiy-b_IQZ6sOBkB5oOk-Jc_NFAB2sL9ktkry3HhVrJQmHPwH4-NCdYziMOrZQwB8pNw2yMTkmx4R84_l1oLRGnx_N4dHmvO09AKqsJLYyNCUjj_djt5aRs3aBMZK5H4zrVLe3DFow3O8jy46iBG6PFkmzJ2B4pgUPddi-dKw3WQZGzABnFynzhbA0bIjBa6-02Dw3EAzDMmAmToNYrBTiS7fe80wR2HBO5jTJbNbQ9_bpeOlIJzklCXHXedU0A6uDBTbC4_ZVKBVfCYMBp3S6oXTcEhebJmYp1ohWxt-svIK1c11F9MyG0hecLURljTtNNxGYwtzLw89Z_K1feU_xI_MOGZPPq-IEt9ztVOGccl5rUbMu_zzxBm_l5bBPpNf73V-_-vaLprZX0xi5fuHZyngrWFGKhh8vavGyDx1HaNk
    hc_vault: []
    age: []
    lastmodified: "2021-10-13T14:42:34Z"
    mac: ENC[AES256_GCM,data:e9gNhT9Z4y6+eLiip+LznuvfjDj+GZYHxq6b1EtrXnIerZHsb6rfBoGle9CJizKh/xSg2DfZtJ6A3CHB1Ha80sAsJJqhMcyiubT/UGc25HIDxS7205U61bLBb0u15AdmJaayvXXWO5x0ItREyNpwqCTYcVUnoYu2HO0PcZ20/tU=,iv:GVwRuyTMYL0QXNSsBpF0m4RkbCRIlHPObWtkqIHW0ro=,tag:MW7b1LmW4cA7o5KE5B7JxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
