apiVersion: v1
kind: Secret
metadata:
    name: common-secret
type: Opaque
data:
    MARIADB_USER: ENC[AES256_GCM,data:OBNwfIQyI60=,iv:PdlGhYmAM5tJmMfiJ9pvs2PsLjYJOg5MX+umSQWFMhc=,tag:bNEzzc2b0+BLq5QZfzpTyQ==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:Nr5NeFSCJvQOmUnrBgGaZp5S5TDRuRyjANcI/4vNPZdIT8Qp6ab3aJtM6GZUDHv17tmWlFwJ3dY=,iv:qT2APlKWhujrARprdwoqoaWBSNsM2G6nYcnALq71mSg=,tag:4fJI8WAOE2yMo101GJFj1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://cscms.vault.azure.net
          name: cscms-k8s-sops-key
          version: bdd9127145c441e2a5d1628e0d32c706
          created_at: "2021-10-26T09:44:36Z"
          enc: X35JqQIeGLPqMBAt9zPg6uoibZsl5r3YY62LDbZic1lHfcWiTb3lsjPObUpHNP3b0s2Cr5b1IcDJ9v7gDq197-Dow3aVtFrZSeEm35kvJprrZtxqFOSv-s4l8s9KPlHf7NIQbMldYO2_32H7H9UCgxtHLrO4h-vNJwWQan-y3-srtOwgcKf3q4IhfJS7_1N_2tu-_bfxbOiEjrifrEVVHUdzYfn6FKHw0UpWQXtCQOrZQlF9W9Qm5gwvVmDa8d61kNlJqfLDtU-bQPyxLElV2pejiZ94722TROPAg4DflSeb7WSKQtD3cuUjAKNXMYxcQz2YxlHf8d2uBal4XjqRbgvZZKU2jpao8wAF0mcwLlN33pujgu8URhrl1jyuuBav3yMV3E7bZfIcOqObYSibcKSOiaCeumsWo1_PMX1zcOE8mJypvcyR6vUIgl0DjoF5tl0ca7KlQ02VCVWcfXdLgZ_w-fneveLAbyaPBfnE7DmYc3znGaVeuoGLpjnil_MO
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T09:44:39Z"
    mac: ENC[AES256_GCM,data:prkdYZnYc9WpHEeUR524NxdWwYMsJhFQRQ0wJeVRNHNuai3n8rbq1V2T2tIojDIrBFaee09nwUbdvqMsrLntTt0ly7VJFTOYPYx49Ja/+czZCY/MQxw7VSYTslgj0aBV5sx7eFCqSE09mbK+1i4QLKfBDmq1OFIFrF1Ta+9vw3s=,iv:cFVLdZvzsIEijxk0iUif2mUrtUBaQR/Bjy94/PHqiXc=,tag:vh/F/2LN7+F3KdhiXAA+RA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
