apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable-api-depl
spec:
  selector:
    matchLabels:
      app: timetable-api
  template:
    metadata:
      labels:
        app: timetable-api
    spec:
      containers:
      - name: timetable-api
        image: thetkpark/cs-timetable-api
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
          requests:
            memory: "32Mi"
            cpu: "1m"
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 4000
          initialDelaySeconds: 120
          failureThreshold: 5
          timeoutSeconds: 2
          periodSeconds: 10

