apiVersion: batch/v1
kind: CronJob
metadata:
  name: cscms-storage-cleaner-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: cscms-storage-vol
            persistentVolumeClaim:
              claimName: cscms-storage-pvc
          containers:
          - name: cscms-storage-cleaner-job
            image: thetkpark/cscms-storage
            imagePullPolicy: Always
            command:
              - /app/cleaner
            envFrom:
              - secretRef:
                  name: cscms-storage-secret
                  optional: false
              - configMapRef:
                  name: cscms-storage-configmap
                  optional: false
            volumeMounts:
              - name: cscms-storage-vol
                mountPath: /mnt/storage-disk
                readOnly: false
                subPath: files
          
  