apiVersion: apps/v1
kind: Deployment
metadata:
  name: cscms-storage-depl
spec:
  selector:
    matchLabels:
      app: cscms-storage-depl
  template:
    metadata:
      labels:
        app: cscms-storage-depl
    spec:
      volumes:
        - name: temp-storage-volume
          azureDisk:
            kind: Managed
            diskName: cscms-temp-storage-disk
            diskURI: /subscriptions/599484bf-47d6-44f0-a3b8-d80b8c8637d6/resourcegroups/MC_cscms.me_cscms-services_southeastasia/providers/Microsoft.Compute/disks/cscms-temp-storage-disk
      containers:
      - name: cscms-storage-depl
        image: thetkpark/cscms-storage
        resources:
          limits:
            # memory: "200Mi"
            cpu: "100m"
          requests:
            memory: "70Mi"
            cpu: "20m"
        envFrom:
          - secretRef:
              name: cscms-storage-secret
              optional: false
          - configMapRef:
              name: cscms-storage-configmap
              optional: false
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: temp-storage-volume
            mountPath: /mnt/storage-disk
            readOnly: false
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/cscms-storage-healthy
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 5000
          initialDelaySeconds: 5
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: common-configmap
                key: MARIADB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: common-configmap
                key: MARIADB_PORT
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: MARIADB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: MARIADB_ROOT_PASSWORD
          - name: DB_DATABASE
            value: cscms-temp-storage
            