apiVersion: v1
kind: Secret
metadata:
    name: cscms-storage-secret
    namespace: cscms-storage
type: Opaque
data:
    DB_PASSWORD: ENC[AES256_GCM,data:SIPQaxZ0q/X0JRyhXU9+Vgk+Fv+se9PUxNiQyZVZZpwKbHnzy/YwOoh9A3fRq4Ampjq/bIByqLE=,iv:Hku9j9d7g02XKapLqlmYSBG2039IxW7+DLLtmHWHH2Q=,tag:CVfNqDBH3iUgCk2sroVycw==,type:str]
    MASTER_KEY: ENC[AES256_GCM,data:DabgdrCLaJzn0cjJSpXT2PuX2pqDgZi3a7KRzHbObl0oU79rz9QuWIEVpqlMNP4HOx7Bx1thipYXpFdZNz1GmFw+faU=,iv:oCp5HnHuPK9xKUpRdU23l+rijNeaNBzb+ltQCBquCWg=,tag:MWq6RaINLJfRac6lVUaGEQ==,type:str]
    AZSTORAGE_CONNECTION_STRING: ENC[AES256_GCM,data:fXHMuR8RWV8DOlDX0d56+iLT7XO/mR6ZEZhmm4v2IrL/KWtUxjLfYRxj7v1AlXSqh1nOLHTfnkyYkkypugQdYx8Rre0LDH1rVPUW2y1FwveAwYnQx6J1tCGmOlDz2RgNWYqcB8agXNwqjUMXpkkmTV6i5ryXPwLO5UGmwKivIkRGXWmWm5sBHPj/HSDspEsFHcKEzi3eXNegtaasm7AiWX/6BzebPOyz7G90VvGMH2sBTauPCd3uQOq5OixqWOrJV1sp1iUcoUIAm46ohs5LDwKFO9q8Ys76iB5EXC4z340QnEOMitIcwBE5CflHxZYdT065OgWjwA8J1g2D,iv:yOftIRaWoRZZtq0Nqz924PvTGjaVW1Sld0DsH3IVGhA=,tag:tEXpmD2OHMSTRymhh8/Qig==,type:str]
    AZSTORAGE_CONTAINER_NAME: ENC[AES256_GCM,data:Zhqyrg==,iv:EXb94ymjcjOUH1mz7HUYnTUfGR9nbSUaeXMw3b6PGgY=,tag:REQcWeSHxA/9V8+PqvA13g==,type:str]
    GITHUB_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:K4PEJIKRgnmfDhfTUWMNZOqZNqRb3s0b4HrnmQ==,iv:6uZA8hOXpBlr3h+TcoRRlYvZonOCNtsLuRvhVHU3DEk=,tag:3E9/yT963nG9XWO2mxovHA==,type:str]
    GITHUB_OAUTH_SECRET_KEY: ENC[AES256_GCM,data:ACCq4ixjz9c0/vuc7ax1vqfUI1rO2KoCCa5p7WUIyHeGmgZk8+5ha1iUqFEuEPjLsM7xRwCqHpY=,iv:bT58xGZdsX9rqUcreefdoOJu9c+D3J5PWkaLlVAMuyc=,tag:upjPm/zd32+r5jOX6Fr64Q==,type:str]
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:nprKsU/pZ3Mu5sDzyzeuiJN3AZFYrJfHh+JR13dZh3+AhvjyDDw789vm/OYrJvp+WDdGOkpolB6Rrkc3MmXEwAtc7HX2vaX7lPz2z8nuGNcthHzoezq1T3tVOhs/wr/a,iv:ENiqLtqPsshtSnCN1OCqHQwoHVdNXbZWZoYJybpJ3x0=,tag:5OmqYSpgbm+Ar6BgikBinQ==,type:str]
    GOOGLE_OAUTH_SECRET_KEY: ENC[AES256_GCM,data:T9/72lQPL5IH7m6UUKIVnPcJA3Rvp9Q9bhR5PlyGkvcbm14hArufUYsCAIg0NrnO,iv:Wqi7xa6BYmWsMi0zPFkjGypw+m4W30pbvv9nqT4Cxk0=,tag:XSDGMXu26mXMvTH7M0svGg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:OAuFgn/pGIvHnLu15Ksl9Jm4fCoIa4LniEzSz7YuVrr3MUnVU5rTeCMpmmbOAj871uHgrUHYTOTZZi+hurM3KzGoKnAskhCD5SJJUhuKw0/sLILoLYbPKbHcKfwy3/JfWoICxKlJtfFDqzY/,iv:g/jH69QPCKj02oUeHGjXKwGawX/5JXkS1U76WFWEm9s=,tag:gyVaUu4Gab5GHeqNS4YqXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MXlTeDhVU3FJMElVam5w
            ZVYyakhlY0Y5Z2l0RjRRY1dJMEtsUHM4cjFvCndXWVF3WnNoeGNmdGRVVHgwZmda
            MnY5ZVdWV0JXTmlVME4zWHBIRWtqMDgKLS0tIENCbWVQZ2RXT0tuTHZUS3lWREV5
            WU9weGdRVXJpSDZmdmZHRW43ak85dXcKPudELMMUntm1LWaFI/+HjaqwOrcxySDg
            RZYOhD9GLQPkPC1kcEBQGeUt6j9YMIKZxRRfeHIL/s3ol0srAcD8wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T03:09:53Z"
    mac: ENC[AES256_GCM,data:UOW0n7pNwq0R/BQREyNnRUPXxsqrVOIpzTRWpBq1KOIDyXTDWPpBkxPu6oRCtBlHxW/vrCNQFKZ+EVtoqR0HBzin268PngJnmuluBnyR1E1zwEN+O9vcKjOYF7fO6ietYi9/oF8v//jxvVDJZRH3FtIklgLBGKgrXJ3nNaIi1D0=,iv:dSr3/eURx7IEbarvqiWJd+Swb9p0KqeP2CzLY3m0hKs=,tag:06ki2MWJO5R4zDf7FMHYPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
