apiVersion: v1
kind: ConfigMap
metadata:
  name: cscms-storage-configmap
data:
  STORE_DURATION: "30"
  STORAGE_PATH: /mnt/storage-disk/data
  PORT: "5000"
  ENTRYPOINT: https://storage.cscms.me
  IMAGE_ENTRYPOINT: https://img.cscms.me