apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cscms-storage-pvc
spec:
  resources:
    requests:
      storage: 32Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
