apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-resources
  namespace: argocd
spec:
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  source:
    path: k8s/nextcloud-resources
    repoURL: https://github.com/thetkpark/cscms-services-deployment.git
    targetRevision: argocd
    directory:
      recurse: true
      exclude: "*.enc.yaml"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    namespace: nextcloud
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://nextcloud.github.io/helm/"
    targetRevision: 4.6.7
    chart: nextcloud
    helm:
      values: |
        replicaCount: 1
        ingress:
          enabled: false
        nextcloud:
          host: nextcloud.cscms.me
          existingSecret:
            enabled: true
            secretName: nextcloud-secret
            usernameKey: username
            passwordKey: password
        internalDatabase:
          enabled: true
          name: nextcloud
        service:
          type: ClusterIP
          port: 8080
        persistence:
          enabled: true
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 128Gi
        resources:
          limits:
            memory: 1.5Gi
          requests:
            cpu: 100m
            memory: 512Mi
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
