apiVersion: apps/v1
kind: Deployment
metadata:
  name: cscms-intern-backend-depl
spec:
  selector:
    matchLabels:
      app: cscms-intern-backend-depl
  template:
    metadata:
      labels:
        app: cscms-intern-backend-depl
    spec:
      containers:
      - name: cscms-intern-backend-depl
        image: thetkpark/cscms-intern-backend
        resources:
          limits:
            memory: "16Mi"
            cpu: "10m"
          requests:
            memory: "8Mi"
            cpu: "5m"
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: common-configmap
                key: MARIADB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: common-configmap
                key: MARIADB_PORT
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: MARIADB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: MARIADB_ROOT_PASSWORD
          - name: DB_DATABASE
            value: cscms-internship
---

apiVersion: v1
kind: Service
metadata:
  name: cscms-intern-backend-srv
spec:
  selector:
    app: cscms-intern-backend-depl
  ports:
  - port: 5000
    targetPort: 5000
