apiVersion: v1
kind: Secret
metadata:
    name: cscms-intern-secret
    namespace: cscms-intern
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:+tKVg6RBpWHychQvvu/fRbm5Ymv9dy19RXjrGbxxounM8LKdMlLnrQ==,iv:FUOviAmeQrz7wdsd7UYWg/nLe8Y16G31Xld9B8yIv/Q=,tag:J+fRHMNKafTECXZ/FwysOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d40qhm7zaxs2xkwzqetdhgju7k8f5ft98uav2we4unqmg684eansa2zcrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZSszQ2tGOWoyY1AxUHph
            TmFoNkdGMUVaQ1FDeEIramVHV01PeWQrYUVvCjcwMnJTYklWbkdrUmJzQVNFbWk0
            cnJ6cU56YVV4cW4wSEhKM1krL2dBNmsKLS0tIGI5WlhlY0xROTlCekFWbG5KSEhN
            c082ZmxSYlpSaGxDb2J3SGZqcUtuUFUKzABcBpIzFIvX3N3r5fYw2d6murQA734r
            MbySHn3JnzEpUggqj53qi8LwLsMQo+Pi5O2J0tRtVlAsNaRDREw3/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T03:09:54Z"
    mac: ENC[AES256_GCM,data:Pin9r48HEYGdRZsR9BAPz2UMPUftd/95s7W8z2XMbXb4B1lo30eq7NBHjec/L1LsKVtIKjnsZI/jsfg65GZJAm0vl9Xg4JoyArV/SvBzXhGYIMgge4TVZRtvPBTZYmiY1pquWyVUBf0wCULn0aXhV/pZePmFPKe3+TCVRV5zElM=,iv:Mn8CJerFec5uz5JeaLWtvVd0MyldnAQSqINwx3b6Ip8=,tag:b4tMlawhM9lIDkYQhOkYkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
