apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone-sync
  namespace: cscms-storage
spec:
  schedule: "15 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: rclone-config
              secret:
                secretName: rclone-config
                optional: false
            - name: target-vol
              persistentVolumeClaim:
                claimName: cscms-storage-pvc
                readOnly: true
          containers:
            - name: rclone
              image: rclone/rclone
              imagePullPolicy: Always
              args:
                - sync
                - /mnt/data
                - cscms-k8s-backup-crypt:cscms-storage
                - --config
                - /config/rclone.conf
              volumeMounts:
                - name: rclone-config
                  mountPath: /config
                  readOnly: false
                - mountPath: /mnt/data
                  name: target-vol
                  readOnly: true
                
