name: Deploy common services & deployments

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
env:
  CLUSTER_NAME: cscms-services
  CLUSTER_RESOURCE_GROUP: cscms.me

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{env.CLUSTER_RESOURCE_GROUP}}
          cluster-name: ${{env.CLUSTER_NAME}}
      - name: Apply ingress config changes
        run: |
          kubectl apply -f k8s/ingress-srv.yaml
          kubectl apply -f k8s/common-configmap.yaml
          kubectl apply -f k8s/redis-common.yaml
